### ISSUE TITLE
wrapAround

### ISSUE THREAD

**Issue by jhowley89** [metafizzy/flickity-sync#2] opened 2015-06-18 16:16 UTC
if the wrapAround option is set to true and you press next on one of the sliders causing it to wrap around the synchronised slider will not wrap around but instead scroll back to the first/last slide.

you can see this by simply adding wrapAround to your existing demo on codepen http://codepen.io/desandro/pen/OPZJmE

this appears to be the same for the asNavFor option, I'm unsure what the difference is between 'asNavFor' and 'sync'

**Comment by desandro** [comment] 2015-06-18 19:54
Thanks for reporting this issue. Closing as a duplicate of metafizzy/flickity#113. Follow along there!

**Closed as completed by desandro** 2015-06-18 19:54 UTC
Labels: duplicate
